# Usar la imagen oficial de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Instalar herramientas necesarias para compilar paquetes, soporte para tkinter y herramientas básicas
RUN apt-get update && apt-get install -y \
    gcc \
    python3-tk \
    iputils-ping \
    netcat-openbsd

# Copiar el código del cliente
COPY client.py /app/client.py

# Instalar dependencias necesarias de Python
RUN pip install --no-cache-dir pickle5

# Configurar la variable de entorno DISPLAY para X11
ENV DISPLAY=host.docker.internal:0

# Comando para ejecutar el cliente (interactivo)
CMD ["python", "client.py"]
