# Usar la imagen oficial de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Instalar herramientas necesarias para compilar paquetes
RUN apt-get update && apt-get install -y gcc

# Copiar el código del servidor
COPY server.py /app/server.py

# Instalar dependencias necesarias
RUN pip install --no-cache-dir pickle5

# Exponer el puerto donde escuchará el servidor
EXPOSE 8080

# Comando para ejecutar el servidor (usando python3 en lugar de python)
CMD ["python", "server.py"]
